name: cron release management
on: 
  schedule:
   - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
      - name: checkout master
        uses: klugem/actions_checkout@v2
        with:
          ref: master
          path: master
      - name: test for new commits since last release
        id: skipTest
        run: |
          echo ::set-output name=SKIP::1
      - name: create a new release
        if: steps.skipTest.outputs.SKIP != 1
        run: |
          echo "running 1 "
