name: cron release management
'on':
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: klugem/actions_checkout@v2
        with:
          ref: master
          path: master
      - name: test for new commits since last release
        id: skipTest
        run: |
          # check if there are some tags
          TAGS=$(git tag | wc -l)
          if [ $TAGS -gt 0 ]; then
            MESSAGE=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)
            LINES=$(echo $MESSAGE | grep -v '^\s*$' | wc -l)
              # new commits since last tag found
              if [ $TAGS -gt 0 ]; then
                echo ::set-output name=SKIP::0
                echo ::set-output name=MESSAGE::0
              else
                echo ::set-output name=SKIP::1
              fi
          else
            echo ::set-output name=SKIP::1
          fi
      - name: create new release
        if: steps.skipTest.outputs.SKIP != 1
        uses: klugem/create-release@v1.0.2
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: '${{ github.ref }}'
          release_name: 'Release ${{ github.ref }}'
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
